name: Preview Links to Linear
on: issue_comment

jobs:
  preview-in-linear:
    if: ${{ github.event.issue.pull_request }}
    name: Preview Links to Linear Issue
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --enable-source-maps
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Attach preview link to Linear issue
        uses: madsnedergaard/preview-link-in-linear@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
